dist: focal
language: node_js
node_js:
  - 16
  - 18
  - 19

before_install:

os:
  - linux
  - osx
  - windows

osx_image:
  - xcode9.4
  - xcode14

jobs:
  exclude:
    - osx_image: xcode9.4
      node_js: 18
    - osx_image: xcode9.4
      node_js: 19
    - osx_image: xcode14
      node_js: 16
    # Only test on linux for regular test jobs
    - if: branch != master
      node_js: 18
    - if: branch != master
      node_js: 19
    - if: type = pull_request
      os: osx
    - if: type = pull_request
      os: windows

script:
  - npm i
  - npm run test-all-lang

