language: minimal

jobs:
  include:
    - name: "Node.js Tests"
      language: node_js
      node_js: "16"
      os:
        - linux
        - osx
        - windows
      script:
        - npm ci
        - npm t

    - name: "Golang Tests"
      language: go
      go: "1.14"
      os:
        - linux
        - osx
        - windows
      script:
        - cd golang/
        - go test 

    - name: "Python Tests"
      language: python
      python: "3.8"
      os:
        - linux
        - osx
        - windows
      script:
        - pip install pytest
        - python -m pytest py/test_rabin.py

